#!/bin/bash

set -x

: ${TIMEOUT:=0}
home=$(readlink --canonicalize ~)
maildir=Mail

if [[ ! -d ~/.offlineimap ]]; then
  mkdir ~/.offlineimap
fi

docker run \
  --rm \
  --env TIMEOUT=${TIMEOUT} \
  --user $(id -u):$(id -g) \
  --volume ${home}/.offlineimap:/var/tmp/.offlineimap:rw \
  --volume ${home}/.offlineimaprc:/var/tmp/.offlineimaprc:ro \
  --volume ${home}/.offlineimap.py:/var/tmp/.offlineimap.py:ro \
  --volume ${home}/${maildir}:/var/tmp/${maildir}:rw \
  offlineimap "$@"
