#!/bin/bash

set -x

: ${TIMEOUT:=300}
home=$(readlink --canonicalize ~)
maildir=Mail

docker run \
  --rm \
  --interactive --tty \
  --env TIMEOUT=${TIMEOUT} \
  --volume ${home}/.offlineimap:/root/.offlineimap:rw \
  --volume ${home}/.offlineimaprc:/root/.offlineimaprc:ro \
  --volume ${home}/.offlineimap.py:/root/.offlineimap.py:ro \
  --volume ${home}/${maildir}:/root/${maildir}:rw \
  offlineimap "$@"
